spring:
    application:
        name: delivery-api

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/delivery
        username: root
        password: password

    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: none

    sql:
        init:
            mode: always
            schema-locations: classpath:schema.sql
            data-locations: classpath:data.sql